version: '3.6'
services:
  recordings:
    build: mod/recordings
    depends_on:
      - redis
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - bigbluebutton:/var/bigbluebutton
      - vol-freeswitch:/var/freeswitch/meetings
      - vol-kurento:/var/kurento
    tmpfs:
      - /var/log/bigbluebutton
      - /tmp
    networks:
      bbb-net:
        ipv4_address: 10.7.7.16